// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbudwyyhqqjiigsgphcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJidWR3eXlocXFqaWlnc2dwaGNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2ODY5MjksImV4cCI6MjA2NjI2MjkyOX0.ZYhrFe0IclEWiMXV_ZxyAE-aLYCrV4G6l6pSWA7MEsE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);